# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 971280133ce6e9850d04920568b58fb22805d59fc0dc890956199d2fba663eef5692c8223a8a96d23b6c6fb882ed28ee8e11acc094ed5717ec1d13ff84e58ba6

test:
  secret_key_base: 14f6210ac8e31127710d4dda21e5d5b89a9fb6cab6096b6723e767c60512272600a2efa56528e2acace48bf50f596b018de1114d17a043a5618a468651a3e4ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
